In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Dell\Desktop\bank.csv",sep=";")

df.isnull().sum()[df.isnull().sum()>0]

import numpy as np
df.replace({'unknown':np.nan},inplace=True)

df.isnull().sum()[df.isnull().sum()>0]

df.job.fillna('admin',inplace=True)
df.marital.fillna('married',inplace=True)
df.default.fillna('no',inplace=True)
df.housing.fillna('yes',inplace=True)
df.loan.fillna('no',inplace=True)
df.education.fillna('university.degree',inplace=True)

df.isnull().sum()[df.isnull().sum()>0]

# Label Encoding wherever required

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['job'] = le.fit_transform(df['job'])
df['marital'] = le.fit_transform(df['marital'])
df['education'] = le.fit_transform(df['education'])
df['housing'] = le.fit_transform(df['housing'])
df['loan'] = le.fit_transform(df['loan'])
df['contact'] = le.fit_transform(df['contact'])
df['month'] = le.fit_transform(df['month'])
df['day_of_week'] = le.fit_transform(df['day_of_week'])
df['poutcome'] = le.fit_transform(df['poutcome'])
df['default'] = le.fit_transform(df['default'])
df['y'] = le.fit_transform(df['y'])

## Selecting important features based on Random Forest

from sklearn.model_selection import train_test_split
df_train , df_test = train_test_split(df , test_size= .2)

df_train_x = df_train.iloc[ : , 0:-1] 
df_train_y = df_train.iloc[ : , -1]

df_test_x = df_test.iloc[ : , 0:-1] 
df_test_y = df_test.iloc[: , -1]
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
from sklearn.ensemble import RandomForestClassifier
rf  = RandomForestClassifier()
rf.fit(df_train_x,df_train_y)
pred_rf = rf.predict(df_test_x)
from sklearn.metrics import confusion_matrix,classification_report
tab_rf = confusion_matrix(df_test_y,pred_rf)
print(tab_rf)
print(classification_report(df_test_y,pred_rf))

importances = rf.feature_importances_
feature_names = df_train_x.columns
feature_importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': importances})
feature_importance_df
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)
print(feature_importance_df)

top_features = feature_importance_df['Feature'][:10].values
selected_features = ['duration', 'euribor3m', 'age', 'nr.employed', 
                     'job', 'education', 'campaign', 'day_of_week', 
                     'pdays', 'cons.conf.idx']


train_df_x_selected = df_train[selected_features]  
test_df_x_selected = df_test[selected_features]


train_df_y = df_train.iloc[:, -1]  # Last column is the target
test_df_y = df_test.iloc[:, -1]

test_df_y = df_test.iloc[:, -1]

from imblearn.over_sampling import SMOTE

train_df_x_selected = df_train[selected_features]  
train_df_y = df_train.iloc[:, -1]  

sm = SMOTE()


x_train_resampled, y_train_resampled = sm.fit_resample(train_df_x_selected, train_df_y)


print("Before Using SMOTE, counts of label '1': {}".format(sum(train_df_y == 1)))
print("Before Using SMOTE, counts of label '0': {} \n".format(sum(train_df_y == 0)))
print("After Using SMOTE, counts of label '1': {}".format(sum(y_train_resampled == 1)))
print("After Using SMOTE, counts of label '0': {} \n".format(sum(y_train_resampled == 0)))


## Standardize the data using any one of the scalers provided by sklearn

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_resampled = scaler.fit_transform(x_train_resampled)
x_test_standardized = scaler.transform(test_df_x_selected)



C:\Users\Dell\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
C:\Users\Dell\AppData\Local\Temp\ipykernel_49524\525566892.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.job.fillna('admin',inplace=True)
C:\Users\Dell\AppData\Local\Temp\ipykernel_49524\525566892.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through c

[[7065  250]
 [ 450  473]]
              precision    recall  f1-score   support

           0       0.94      0.97      0.95      7315
           1       0.65      0.51      0.57       923

    accuracy                           0.92      8238
   macro avg       0.80      0.74      0.76      8238
weighted avg       0.91      0.92      0.91      8238

           Feature    Importance
10        duration  3.224916e-01
18       euribor3m  1.088398e-01
0              age  9.676307e-02
19     nr.employed  7.056153e-02
1              job  5.063189e-02
11        campaign  4.342989e-02
9      day_of_week  4.191917e-02
3        education  4.028164e-02
14        poutcome  3.126136e-02
12           pdays  2.816091e-02
17   cons.conf.idx  2.654827e-02
2          marital  2.370926e-02
16  cons.price.idx  2.009741e-02
15    emp.var.rate  1.962132e-02
8            month  1.938374e-02
5          housing  1.874884e-02
13        previous  1.464531e-02
6             loan  1.281241e-02
7          contact 

### Tabulate the performance metrics of all the above models, perform tuning of models and tell which model performs better in predicting if the client will subscribe to term deposit or not

### 1.Logistic Regression

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix, precision_score, recall_score, f1_score


logreg = LogisticRegression(class_weight='balanced')


param_grid_logreg = {
    'C': [0.1, 1, 10],  # Regularization strength
    'solver': ['liblinear']  # Solvers
}


grid_search_logreg = GridSearchCV(logreg, param_grid_logreg, scoring='precision', cv=5)
grid_search_logreg.fit(x_train_resampled, y_train_resampled)


best_logreg_params = grid_search_logreg.best_params_
best_logreg_score = grid_search_logreg.best_score_


print(f"Best Logistic Regression Parameters: {best_logreg_params}")
print(f"Best Precision Score for Logistic Regression: {best_logreg_score}")


best_logreg = grid_search_logreg.best_estimator_


y_pred_logreg = best_logreg.predict(x_test_standardized)


accuracy_logreg = best_logreg.score(x_test_standardized, test_df_y)
precision_logreg = precision_score(test_df_y, y_pred_logreg)
recall_logreg = recall_score(test_df_y, y_pred_logreg)
f1_logreg = f1_score(test_df_y, y_pred_logreg)
conf_matrix_logreg = confusion_matrix(test_df_y, y_pred_logreg)
class_report_logreg = classification_report(test_df_y, y_pred_logreg)


print("\nLogistic Regression Performance:")
print(f"Accuracy: {accuracy_logreg}")
print(f"Precision: {precision_logreg}")
print(f"Recall: {recall_logreg}")
print(f"F1-Score: {f1_logreg}")
print("Confusion Matrix:")
print(conf_matrix_logreg)
print("\nClassification Report:")
print(class_report_logreg)


Best Logistic Regression Parameters: {'C': 10, 'solver': 'liblinear'}
Best Precision Score for Logistic Regression: 0.8480444973002399

Logistic Regression Performance:
Accuracy: 0.8492352512745812
Precision: 0.4146602461209203
Recall: 0.8396533044420368
F1-Score: 0.5551575931232091
Confusion Matrix:
[[6221 1094]
 [ 148  775]]

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.85      0.91      7315
           1       0.41      0.84      0.56       923

    accuracy                           0.85      8238
   macro avg       0.70      0.85      0.73      8238
weighted avg       0.91      0.85      0.87      8238



In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix, precision_score, recall_score, f1_score


dtc = DecisionTreeClassifier(random_state=42)


param_grid_dtc = {
    'max_depth': [10, 20, 30, None],  # Maximum depth of tree
    'min_samples_split': [2, 5, 10],  # Minimum samples required to split
    'min_samples_leaf': [1, 2, 4],  # Minimum samples required at leaf node
    'criterion': ['gini', 'entropy']  # Split criteria
}


grid_search_dtc = GridSearchCV(dtc, param_grid_dtc, scoring='precision', cv=5)
grid_search_dtc.fit(x_train_resampled, y_train_resampled)


best_dtc_params = grid_search_dtc.best_params_
best_dtc_score = grid_search_dtc.best_score_

print(f"Best Decision Tree Parameters: {best_dtc_params}")
print(f"Best Precision Score for Decision Tree: {best_dtc_score}")


best_dtc = grid_search_dtc.best_estimator_


y_pred_dtc = best_dtc.predict(x_test_standardized)


accuracy_dtc = best_dtc.score(x_test_standardized, test_df_y)
precision_dtc = precision_score(test_df_y, y_pred_dtc)
recall_dtc = recall_score(test_df_y, y_pred_dtc)
f1_dtc = f1_score(test_df_y, y_pred_dtc)
conf_matrix_dtc = confusion_matrix(test_df_y, y_pred_dtc)
class_report_dtc = classification_report(test_df_y, y_pred_dtc)


print("\nDecision Tree Performance:")
print(f"Accuracy: {accuracy_dtc}")
print(f"Precision: {precision_dtc}")
print(f"Recall: {recall_dtc}")
print(f"F1-Score: {f1_dtc}")
print("Confusion Matrix:")
print(conf_matrix_dtc)
print("\nClassification Report:")
print(class_report_dtc)


Best Decision Tree Parameters: {'criterion': 'gini', 'max_depth': 30, 'min_samples_leaf': 2, 'min_samples_split': 2}
Best Precision Score for Decision Tree: 0.9298691402786188

Decision Tree Performance:
Accuracy: 0.8895362952172857
Precision: 0.5067920585161965
Recall: 0.5254604550379198
F1-Score: 0.5159574468085106
Confusion Matrix:
[[6843  472]
 [ 438  485]]

Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.94      0.94      7315
           1       0.51      0.53      0.52       923

    accuracy                           0.89      8238
   macro avg       0.72      0.73      0.73      8238
weighted avg       0.89      0.89      0.89      8238



In [4]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import classification_report, confusion_matrix, precision_score, recall_score, f1_score


rfc = RandomForestClassifier()


param_grid_rfc = {
    'n_estimators': [50, 100],  # Fewer estimators
    'max_depth': [10, 20],  # Reduced depth range
    'min_samples_split': [2, 5],  # Reduced options
    'min_samples_leaf': [1, 2],  # Reduced options
    'criterion': ['gini']  # Keeping only one criterion
}


random_search_rfc = RandomizedSearchCV(rfc, param_grid_rfc, n_iter=10, scoring='precision', cv=3, n_jobs=-1, random_state=42)
random_search_rfc.fit(x_train_resampled, y_train_resampled)


best_rfc_params = random_search_rfc.best_params_
best_rfc_score = random_search_rfc.best_score_

print(f"Best Random Forest Parameters: {best_rfc_params}")
print(f"Best Precision Score for Random Forest: {best_rfc_score}")


best_rfc = random_search_rfc.best_estimator_


y_pred_rfc = best_rfc.predict(x_test_standardized)


accuracy_rfc = best_rfc.score(x_test_standardized, test_df_y)
precision_rfc = precision_score(test_df_y, y_pred_rfc)
recall_rfc = recall_score(test_df_y, y_pred_rfc)
f1_rfc = f1_score(test_df_y, y_pred_rfc)
conf_matrix_rfc = confusion_matrix(test_df_y, y_pred_rfc)
class_report_rfc = classification_report(test_df_y, y_pred_rfc)


print("\nRandom Forest Performance:")
print(f"Accuracy: {accuracy_rfc}")
print(f"Precision: {precision_rfc}")
print(f"Recall: {recall_rfc}")
print(f"F1-Score: {f1_rfc}")
print("Confusion Matrix:")
print(conf_matrix_rfc)
print("\nClassification Report:")
print(class_report_rfc)


Best Random Forest Parameters: {'n_estimators': 100, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_depth': 20, 'criterion': 'gini'}
Best Precision Score for Random Forest: 0.9282491390245059

Random Forest Performance:
Accuracy: 0.9056809905316825
Precision: 0.5627147766323024
Recall: 0.7096424702058505
F1-Score: 0.6276952563488261
Confusion Matrix:
[[6806  509]
 [ 268  655]]

Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.93      0.95      7315
           1       0.56      0.71      0.63       923

    accuracy                           0.91      8238
   macro avg       0.76      0.82      0.79      8238
weighted avg       0.92      0.91      0.91      8238

